version: "3"

services:
  web:
    build: .
    command: python3 backend/manage.py runserver 0.0.0.0:4000
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/backend
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - /var/lib/postgresql/data
