# Generated by Django 3.0.3 on 2021-03-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('organization', models.TextField()),
                ('phones', models.TextField()),
                ('emails', models.CharField(max_length=30)),
                ('notes', models.TextField()),
            ],
        ),
    ]
